### ISSUE TITLE
MINOR: Extra console.log statements

### ISSUE THREAD

**Issue by thejameskim** [BeckMillet/INFO442Team5#43]
**Describe the bug**
Extra console.log statements appear on the main page: “today is: 6/3/2020”

**To Reproduce**
1. Log in to the application
2. Opening up developer’s console.

**Expected behavior**
No console.log statements

**Screenshots**
<img width="405" alt="Sprout - Extra console log statements" src="https://user-images.githubusercontent.com/15903829/83665955-0915a880-a581-11ea-9363-6a21c706f579.png">

**Additional context**
Logging errors and information to the console, you can risk sharing sensitive data about your application structure.

**Comment by thoalala** [comment]
@thejameskim Thanks for reporting! We will fix this in the next release. As it doesn't break any functionality, I agree that its a minor bug and we should have prettier or a linter do this for us. Possibly an enhancement to the commit/build pipeline.

**Comment by thoalala** [comment]
Not in scope and doesn't affect functionality. Given the current situation, our team has decided not to fix it.
