### ISSUE TITLE
MINOR: Item name more than 25 characters

### ISSUE THREAD

**Issue by thejameskim** [BeckMillet/INFO442Team5#44]
**Describe the bug**
Wasn't sure why the application was not submitting my response until I noticed the 25 character limit after clicking submit

**To Reproduce**
1. Log in to the application
2. Typing in more than 25 characters into item name.
3. Clicking submit

**Expected behavior**
A message or feedback that more than 25 characters are not allowed.

**Screenshots**
<img width="1668" alt="Sprout - No feedback on 25 character limit" src="https://user-images.githubusercontent.com/15903829/83666813-64946600-a582-11ea-9971-064c36cae56c.png">

**Rationale**
Since no message was given, why the submission was not working could be confusing to some users. Users cannot address the issue without proper messaging which can lead to poor user experience.

**Comment by angelashen0607** [comment]
At this stage, we feel like having a red border around once the user inputs more than 25 characters (which is also not likely) indicates that something is wrong already.
