### ISSUE TITLE
MAJOR: Different Date & Same Budget

### ISSUE THREAD

**Issue by skymrsn** [BeckMillet/INFO442Team5#45]
**Describe the bug**
Assume today' date is June 3rd. I give myself 100 dollars daily budget for today, everything works fine when I add spending to today. However, when I added spending on June 4th, my budget on June 3rd also get deducted. Spending on different days should not be reflected on budget which does not match. 

**To Reproduce**
1. Set daily budget 100 dollars (On June 3rd). 
2. Click on update. 
3. Add spending on June 3rd.
4. Add spending on June 4th.
5. Budget for June 3rd reflected the spending on 4th. 

**Expected behavior**
Spending on June 4th should not affect the budget on June 3rd. Users expect daily budget.

**Comment by thoalala** [comment]
We resolved this bug based on the user's system date but not for a transaction that occurs in the future. 

- For example, this user entered a June 4th transaction that was calculated into the overall balance of June 3rd. Lets resolved by restricting transactions that occur after the "today's date". 

I know we discussed whether this was a bug already but if the solution can be implemented let's try it. I also remember Maxwell stating that restricting future transactions could be problematic. If so, let the team know and we can explain why we won't fix this bug.

**Comment by thoalala** [comment]
@skymrsn Just to confirm, you added a new transaction with the June 4th date on the calendar drop-down menu. You didn't change the "Today's Date" to June 4th and entered new transactions.

**Comment by skymrsn** [comment]
> @skymrsn Just to confirm, you added a new transaction with the June 4th date on the calendar drop-down menu. You didn't change the "Today's Date" to June 4th and entered new transactions.

No, I did not.

**Comment by thoalala** [comment]
#49

**Comment by kevin-chiu** [comment]
Being allowed to document future transactions does not disrupt or break the functionality of the project. As this issue does not pertain to our requirements, we will not be making changes.
