### ISSUE TITLE
MAJOR: Transaction Decimal Submission Issues

### ISSUE THREAD

**Issue by ShrutiR5** [BeckMillet/INFO442Team5#47]
**Describe the bug**
If you add a transaction with three decimal places and extremely small, the overall budget does not update and I can't submit it. 

**To Reproduce**
1. Go to add a budget and add the budget ($30).
2. Click on the Item name - add name.
3. Scroll down to amount insert a small amount to 3 decimal places (0.004).
4. Error: Won't let me submit.

**Expected behavior**
It's supposed to let me submit and update my overall balance. 

**Smartphone:**
 - Device: iPhoneX 

**Screenshot**:
<img width="265" alt="Screen Shot 2020-06-03 at 5 22 27 PM" src="https://user-images.githubusercontent.com/35204568/83701607-ffab3100-a5be-11ea-83b5-c0d6419dc77f.png">

**Additional context**
N/A

**Comment by thoalala** [comment]
@ShrutiR5 Cannot reproduce. Could you take a screenshot of the exact transaction and the overall balance?

**Comment by thoalala** [comment]
While testing, I noticed that users cannot enter transactions that are super small. For example: $0.003. Flagged for review. 

![image](https://user-images.githubusercontent.com/24668595/83701272-01282980-a5be-11ea-8f87-c3edfc12544f.png)

**Comment by ShrutiR5** [comment]
Changed the above report to re-frame the bug.

**Comment by thoalala** [comment]
Team: Not sure if this is a major issue. Yes, submit functionality cannot be accomplished but monetary transactions are rounded to 2 decimal places. A workaround exists - users can round to the second decimal. Is there such thing as a .004 charge? In addition, users can add 1.004 and the backend overall balance is calculated correctly by accounting for the .004 but rounded to the 2 decimal place for aesthetic. Let's fix if we do agree that it's an issue.

**Comment by thoalala** [comment]
Looking back at this, I believe that this may be a minor issue as it's not breaking any functionality. Yes, I agree that this type of input shouldn't be allowed, but that would be a matter of form validation on our end / not providing a clear error message. 

@bmaxwell99 Could you look into adding an extra form validation on the number input or assign as needed? 

@ShrutiR5 
Thanks for the issue! Look out for a fix in the next release. Lmk if we can reprioritize this as a minor bug.

**Comment by shannongatta1** [comment]
As a workaround,  users can round to the second decimal. Because of this capability, we see this as a minor issue, and will not be making changes.
