### ISSUE TITLE
MAJOR: **Unable to click "Add Event" Button when on mobile screen size**

### ISSUE THREAD

**Issue by Janette-cwk** [BeckMillet/INFO442Team5#51]
**Describe the bug**
When using mobile screen size, the top nav bar cover up the "Add Event" button on the "Calendar" page. I was not able to click it. 

**To Reproduce**
1. Go to Landing page
2. Click on Sign in
3. Click "Calendar" tab

**Expected behavior**
I expected the "Add Event" button won't get cover up by the top nav bar, so that I can click it.

**Screenshots**
![image](https://user-images.githubusercontent.com/43595741/83706055-5b7bb700-a5cb-11ea-8213-4bf73109ad70.png)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - Browser: safari

**Comment by thoalala** [comment]
@Janette-cwk I believe this may be the wrong repository. Closing.
