### ISSUE TITLE
MINOR: Can type in a future date, and will display "Invalid date"

### ISSUE THREAD

**Issue by eddyhuang97** [BeckMillet/INFO442Team5#56]
**Describe the bug**
I can type in a future date under transaction

**To Reproduce**
1. Login
2. Under transaction, type in a future date. For me I entered June 8th which is tomorrow
3. Click submit

**Expected behavior**
Under latest activity, the new item will display "invalid date"

**Rationale**
It might be useful to help the user check the date, since they might accidentally put in the wrong date and the "invalid date" might confuse some people

**Screenshots**
<img width="593" alt="Screen Shot 2020-06-07 at 5 02 45 PM" src="https://user-images.githubusercontent.com/32340414/83983125-c5080800-a8e0-11ea-86c4-d5c5d7ef6940.png">

**Comment by thoalala** [comment]
**Team:** This may be the result of fixing the date and transaction errors that were previously filed. I don't think this is a bug because it is by design that users cannot enter transactions from future dates. Let's categorized as not an failure or discuss it on Monday.

**Comment by thoalala** [comment]
Not a real failure. By design, the users cannot enter transactions from future dates.
