### ISSUE TITLE
MINOR: When entering a negative number, there is no prompt saying positive number only

### ISSUE THREAD

**Issue by eddyhuang97** [BeckMillet/INFO442Team5#57]
**Describe the bug**
When entering a negative number, there is no prompt saying positive number only

**To Reproduce**
1. Login
2. Create a new item with a negative number
3. Click submit

**Expected behavior**
I expected it to say something along the line of "you cannot put in a negative number. But it did not show up. Only a red box appeared.

**Rationale**
This is not a big problem, but some additional detail might help the user understand the problem so they can fix it

**Screenshots**
<img width="851" alt="Screen Shot 2020-06-07 at 5 05 48 PM" src="https://user-images.githubusercontent.com/32340414/83983241-8888dc00-a8e1-11ea-820a-e9122c0a8e98.png">

**Comment by angelashen0607** [comment]
The red border around the input box indicates that there is something wrong and since it is very unlikely for users to input negative numbers, we think that this is a non-failure issue that doesn't affect the app's functionality.
