### ISSUE TITLE
MINOR: **No error message for non-number entries**

### ISSUE THREAD

**Issue by kylerws** [BeckMillet/INFO442Team5#58]
**Describe the bug**
If you enter a non-numeric value for the daily budget, the system will display an error message stating "Must be positive and non-zero"

**To Reproduce**
1. Enter any non-numeric value for daily budget

**Expected behavior**
Display a unique error message along the lines of "Must enter a number"

**Screenshots**
![sprout_cap_1](https://user-images.githubusercontent.com/35178890/84088096-96516680-a9a0-11ea-89f8-2ef2ed3858e8.JPG)

**Comment by thoalala** [comment]
Team:  Not a real failure. We already have an error message and It’s implied that positive and non zero references number. If we wanted to come back to this issue in the future, we can just update the error message to say "must be positive and non zero number. " Tagging not a real failure and closing for now.
