### ISSUE TITLE
MINOR: How many transactions? Categories?

### ISSUE THREAD

**Issue by edwardhalimm** [BeckMillet/INFO442Team5#59]
**Describe the bug**
The app does not show the number of the transactions I made. I think it'd be useful for user to know how many times they spent. 

**To Reproduce**
Create transaction multiple times. 

**Expected behavior**
It numbered my transactions. And it'd be better if they have categorize feature so you know what you spent the most

**Smartphone (please complete the following information):**
 Macbook, chrome

**Additional context**
Put the enter transaction on the left, and the latest activity on the right. So user doesn't have to scroll down.

**Comment by thoalala** [comment]
Thanks for reporting!
Team: This is not a real failure. The continuous scrolling is apart of our UX flow and categories are not within our project's scope. It can be categorized as an enhancement for a future release should we choose to do so.
